<?php

namespace Database\Seeders\Examples;

use App\Models\Examples\ExampleType;
use Illuminate\Database\Seeder;

class ExampleTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seeding custom data
        ExampleType::factory()->createMany($this->data);
        // Seeding random data
        ExampleType::factory()->times(20)->create();
    }

    // CUSTOM DATA

    private $data = [
        [
            "name" => "Example type 1",
            // Field "status" is generated by the factory, therefore it inherits the given value
        ],
        [
            "name" => "Example type 2",
            // Field "status" is generated by the factory, therefore it inherits the given value
        ],
        [
            "name" => "Example type 3",
            // Field "status" is generated by the factory, therefore it inherits the given value
        ],
        [
            "name" => "Example type 4",
            // Field "status" is generated by the factory, therefore it inherits the given value
        ],

    ];
}
